/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kolanot.service.service.base;

import com.kolanot.service.model.KolanotInvoice;
import com.kolanot.service.service.KolanotInvoiceLocalService;
import com.kolanot.service.service.persistence.KolanotInvoiceLinePersistence;
import com.kolanot.service.service.persistence.KolanotInvoicePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the kolanot invoice local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.kolanot.service.service.impl.KolanotInvoiceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.kolanot.service.service.impl.KolanotInvoiceLocalServiceImpl
 * @generated
 */
public abstract class KolanotInvoiceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, KolanotInvoiceLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>KolanotInvoiceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.kolanot.service.service.KolanotInvoiceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the kolanot invoice to the database. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoice the kolanot invoice
	 * @return the kolanot invoice that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KolanotInvoice addKolanotInvoice(KolanotInvoice kolanotInvoice) {
		kolanotInvoice.setNew(true);

		return kolanotInvoicePersistence.update(kolanotInvoice);
	}

	/**
	 * Creates a new kolanot invoice with the primary key. Does not add the kolanot invoice to the database.
	 *
	 * @param invoiceId the primary key for the new kolanot invoice
	 * @return the new kolanot invoice
	 */
	@Override
	@Transactional(enabled = false)
	public KolanotInvoice createKolanotInvoice(long invoiceId) {
		return kolanotInvoicePersistence.create(invoiceId);
	}

	/**
	 * Deletes the kolanot invoice with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param invoiceId the primary key of the kolanot invoice
	 * @return the kolanot invoice that was removed
	 * @throws PortalException if a kolanot invoice with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KolanotInvoice deleteKolanotInvoice(long invoiceId)
		throws PortalException {

		return kolanotInvoicePersistence.remove(invoiceId);
	}

	/**
	 * Deletes the kolanot invoice from the database. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoice the kolanot invoice
	 * @return the kolanot invoice that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KolanotInvoice deleteKolanotInvoice(KolanotInvoice kolanotInvoice) {
		return kolanotInvoicePersistence.remove(kolanotInvoice);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			KolanotInvoice.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return kolanotInvoicePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return kolanotInvoicePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return kolanotInvoicePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return kolanotInvoicePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return kolanotInvoicePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public KolanotInvoice fetchKolanotInvoice(long invoiceId) {
		return kolanotInvoicePersistence.fetchByPrimaryKey(invoiceId);
	}

	/**
	 * Returns the kolanot invoice matching the UUID and group.
	 *
	 * @param uuid the kolanot invoice's UUID
	 * @param groupId the primary key of the group
	 * @return the matching kolanot invoice, or <code>null</code> if a matching kolanot invoice could not be found
	 */
	@Override
	public KolanotInvoice fetchKolanotInvoiceByUuidAndGroupId(
		String uuid, long groupId) {

		return kolanotInvoicePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the kolanot invoice with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the kolanot invoice's external reference code
	 * @return the matching kolanot invoice, or <code>null</code> if a matching kolanot invoice could not be found
	 */
	@Override
	public KolanotInvoice fetchKolanotInvoiceByReferenceCode(
		long companyId, String externalReferenceCode) {

		return kolanotInvoicePersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the kolanot invoice with the primary key.
	 *
	 * @param invoiceId the primary key of the kolanot invoice
	 * @return the kolanot invoice
	 * @throws PortalException if a kolanot invoice with the primary key could not be found
	 */
	@Override
	public KolanotInvoice getKolanotInvoice(long invoiceId)
		throws PortalException {

		return kolanotInvoicePersistence.findByPrimaryKey(invoiceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(kolanotInvoiceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KolanotInvoice.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("invoiceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			kolanotInvoiceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(KolanotInvoice.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("invoiceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(kolanotInvoiceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KolanotInvoice.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("invoiceId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<KolanotInvoice>() {

				@Override
				public void performAction(KolanotInvoice kolanotInvoice)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, kolanotInvoice);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(KolanotInvoice.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return kolanotInvoicePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return kolanotInvoiceLocalService.deleteKolanotInvoice(
			(KolanotInvoice)persistedModel);
	}

	public BasePersistence<KolanotInvoice> getBasePersistence() {
		return kolanotInvoicePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return kolanotInvoicePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the kolanot invoices matching the UUID and company.
	 *
	 * @param uuid the UUID of the kolanot invoices
	 * @param companyId the primary key of the company
	 * @return the matching kolanot invoices, or an empty list if no matches were found
	 */
	@Override
	public List<KolanotInvoice> getKolanotInvoicesByUuidAndCompanyId(
		String uuid, long companyId) {

		return kolanotInvoicePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of kolanot invoices matching the UUID and company.
	 *
	 * @param uuid the UUID of the kolanot invoices
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of kolanot invoices
	 * @param end the upper bound of the range of kolanot invoices (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching kolanot invoices, or an empty list if no matches were found
	 */
	@Override
	public List<KolanotInvoice> getKolanotInvoicesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<KolanotInvoice> orderByComparator) {

		return kolanotInvoicePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the kolanot invoice matching the UUID and group.
	 *
	 * @param uuid the kolanot invoice's UUID
	 * @param groupId the primary key of the group
	 * @return the matching kolanot invoice
	 * @throws PortalException if a matching kolanot invoice could not be found
	 */
	@Override
	public KolanotInvoice getKolanotInvoiceByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return kolanotInvoicePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the kolanot invoices.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of kolanot invoices
	 * @param end the upper bound of the range of kolanot invoices (not inclusive)
	 * @return the range of kolanot invoices
	 */
	@Override
	public List<KolanotInvoice> getKolanotInvoices(int start, int end) {
		return kolanotInvoicePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of kolanot invoices.
	 *
	 * @return the number of kolanot invoices
	 */
	@Override
	public int getKolanotInvoicesCount() {
		return kolanotInvoicePersistence.countAll();
	}

	/**
	 * Updates the kolanot invoice in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoice the kolanot invoice
	 * @return the kolanot invoice that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KolanotInvoice updateKolanotInvoice(KolanotInvoice kolanotInvoice) {
		return kolanotInvoicePersistence.update(kolanotInvoice);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			KolanotInvoiceLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		kolanotInvoiceLocalService = (KolanotInvoiceLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return KolanotInvoiceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return KolanotInvoice.class;
	}

	protected String getModelClassName() {
		return KolanotInvoice.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = kolanotInvoicePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected KolanotInvoiceLocalService kolanotInvoiceLocalService;

	@Reference
	protected KolanotInvoicePersistence kolanotInvoicePersistence;

	@Reference
	protected KolanotInvoiceLinePersistence kolanotInvoiceLinePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}