/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kolanot.service.service.base;

import com.kolanot.service.model.KolanotInvoiceLine;
import com.kolanot.service.service.KolanotInvoiceLineLocalService;
import com.kolanot.service.service.persistence.KolanotInvoiceLinePersistence;
import com.kolanot.service.service.persistence.KolanotInvoicePersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the kolanot invoice line local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.kolanot.service.service.impl.KolanotInvoiceLineLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.kolanot.service.service.impl.KolanotInvoiceLineLocalServiceImpl
 * @generated
 */
public abstract class KolanotInvoiceLineLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   KolanotInvoiceLineLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>KolanotInvoiceLineLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.kolanot.service.service.KolanotInvoiceLineLocalServiceUtil</code>.
	 */

	/**
	 * Adds the kolanot invoice line to the database. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoiceLine the kolanot invoice line
	 * @return the kolanot invoice line that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KolanotInvoiceLine addKolanotInvoiceLine(
		KolanotInvoiceLine kolanotInvoiceLine) {

		kolanotInvoiceLine.setNew(true);

		return kolanotInvoiceLinePersistence.update(kolanotInvoiceLine);
	}

	/**
	 * Creates a new kolanot invoice line with the primary key. Does not add the kolanot invoice line to the database.
	 *
	 * @param invoiceLineId the primary key for the new kolanot invoice line
	 * @return the new kolanot invoice line
	 */
	@Override
	@Transactional(enabled = false)
	public KolanotInvoiceLine createKolanotInvoiceLine(long invoiceLineId) {
		return kolanotInvoiceLinePersistence.create(invoiceLineId);
	}

	/**
	 * Deletes the kolanot invoice line with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param invoiceLineId the primary key of the kolanot invoice line
	 * @return the kolanot invoice line that was removed
	 * @throws PortalException if a kolanot invoice line with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KolanotInvoiceLine deleteKolanotInvoiceLine(long invoiceLineId)
		throws PortalException {

		return kolanotInvoiceLinePersistence.remove(invoiceLineId);
	}

	/**
	 * Deletes the kolanot invoice line from the database. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoiceLine the kolanot invoice line
	 * @return the kolanot invoice line that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KolanotInvoiceLine deleteKolanotInvoiceLine(
		KolanotInvoiceLine kolanotInvoiceLine) {

		return kolanotInvoiceLinePersistence.remove(kolanotInvoiceLine);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			KolanotInvoiceLine.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return kolanotInvoiceLinePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceLineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return kolanotInvoiceLinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceLineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return kolanotInvoiceLinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return kolanotInvoiceLinePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return kolanotInvoiceLinePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public KolanotInvoiceLine fetchKolanotInvoiceLine(long invoiceLineId) {
		return kolanotInvoiceLinePersistence.fetchByPrimaryKey(invoiceLineId);
	}

	/**
	 * Returns the kolanot invoice line matching the UUID and group.
	 *
	 * @param uuid the kolanot invoice line's UUID
	 * @param groupId the primary key of the group
	 * @return the matching kolanot invoice line, or <code>null</code> if a matching kolanot invoice line could not be found
	 */
	@Override
	public KolanotInvoiceLine fetchKolanotInvoiceLineByUuidAndGroupId(
		String uuid, long groupId) {

		return kolanotInvoiceLinePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the kolanot invoice line with the primary key.
	 *
	 * @param invoiceLineId the primary key of the kolanot invoice line
	 * @return the kolanot invoice line
	 * @throws PortalException if a kolanot invoice line with the primary key could not be found
	 */
	@Override
	public KolanotInvoiceLine getKolanotInvoiceLine(long invoiceLineId)
		throws PortalException {

		return kolanotInvoiceLinePersistence.findByPrimaryKey(invoiceLineId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			kolanotInvoiceLineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KolanotInvoiceLine.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("invoiceLineId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			kolanotInvoiceLineLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(KolanotInvoiceLine.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"invoiceLineId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			kolanotInvoiceLineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KolanotInvoiceLine.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("invoiceLineId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return kolanotInvoiceLinePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return kolanotInvoiceLineLocalService.deleteKolanotInvoiceLine(
			(KolanotInvoiceLine)persistedModel);
	}

	public BasePersistence<KolanotInvoiceLine> getBasePersistence() {
		return kolanotInvoiceLinePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return kolanotInvoiceLinePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the kolanot invoice lines matching the UUID and company.
	 *
	 * @param uuid the UUID of the kolanot invoice lines
	 * @param companyId the primary key of the company
	 * @return the matching kolanot invoice lines, or an empty list if no matches were found
	 */
	@Override
	public List<KolanotInvoiceLine> getKolanotInvoiceLinesByUuidAndCompanyId(
		String uuid, long companyId) {

		return kolanotInvoiceLinePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of kolanot invoice lines matching the UUID and company.
	 *
	 * @param uuid the UUID of the kolanot invoice lines
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of kolanot invoice lines
	 * @param end the upper bound of the range of kolanot invoice lines (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching kolanot invoice lines, or an empty list if no matches were found
	 */
	@Override
	public List<KolanotInvoiceLine> getKolanotInvoiceLinesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<KolanotInvoiceLine> orderByComparator) {

		return kolanotInvoiceLinePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the kolanot invoice line matching the UUID and group.
	 *
	 * @param uuid the kolanot invoice line's UUID
	 * @param groupId the primary key of the group
	 * @return the matching kolanot invoice line
	 * @throws PortalException if a matching kolanot invoice line could not be found
	 */
	@Override
	public KolanotInvoiceLine getKolanotInvoiceLineByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return kolanotInvoiceLinePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the kolanot invoice lines.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.kolanot.service.model.impl.KolanotInvoiceLineModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of kolanot invoice lines
	 * @param end the upper bound of the range of kolanot invoice lines (not inclusive)
	 * @return the range of kolanot invoice lines
	 */
	@Override
	public List<KolanotInvoiceLine> getKolanotInvoiceLines(int start, int end) {
		return kolanotInvoiceLinePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of kolanot invoice lines.
	 *
	 * @return the number of kolanot invoice lines
	 */
	@Override
	public int getKolanotInvoiceLinesCount() {
		return kolanotInvoiceLinePersistence.countAll();
	}

	/**
	 * Updates the kolanot invoice line in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param kolanotInvoiceLine the kolanot invoice line
	 * @return the kolanot invoice line that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KolanotInvoiceLine updateKolanotInvoiceLine(
		KolanotInvoiceLine kolanotInvoiceLine) {

		return kolanotInvoiceLinePersistence.update(kolanotInvoiceLine);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			KolanotInvoiceLineLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		kolanotInvoiceLineLocalService =
			(KolanotInvoiceLineLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return KolanotInvoiceLineLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return KolanotInvoiceLine.class;
	}

	protected String getModelClassName() {
		return KolanotInvoiceLine.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				kolanotInvoiceLinePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected KolanotInvoicePersistence kolanotInvoicePersistence;

	protected KolanotInvoiceLineLocalService kolanotInvoiceLineLocalService;

	@Reference
	protected KolanotInvoiceLinePersistence kolanotInvoiceLinePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}