/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kolanot.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.math.BigDecimal;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KolanotInvoiceLine service. Represents a row in the &quot;kolanot_KolanotInvoiceLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kolanot.service.model.impl.KolanotInvoiceLineModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kolanot.service.model.impl.KolanotInvoiceLineImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KolanotInvoiceLine
 * @generated
 */
@ProviderType
public interface KolanotInvoiceLineModel
	extends BaseModel<KolanotInvoiceLine>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kolanot invoice line model instance should use the {@link KolanotInvoiceLine} interface instead.
	 */

	/**
	 * Returns the primary key of this kolanot invoice line.
	 *
	 * @return the primary key of this kolanot invoice line
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kolanot invoice line.
	 *
	 * @param primaryKey the primary key of this kolanot invoice line
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this kolanot invoice line.
	 *
	 * @return the uuid of this kolanot invoice line
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this kolanot invoice line.
	 *
	 * @param uuid the uuid of this kolanot invoice line
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the invoice line ID of this kolanot invoice line.
	 *
	 * @return the invoice line ID of this kolanot invoice line
	 */
	public long getInvoiceLineId();

	/**
	 * Sets the invoice line ID of this kolanot invoice line.
	 *
	 * @param invoiceLineId the invoice line ID of this kolanot invoice line
	 */
	public void setInvoiceLineId(long invoiceLineId);

	/**
	 * Returns the group ID of this kolanot invoice line.
	 *
	 * @return the group ID of this kolanot invoice line
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this kolanot invoice line.
	 *
	 * @param groupId the group ID of this kolanot invoice line
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the invoice ID of this kolanot invoice line.
	 *
	 * @return the invoice ID of this kolanot invoice line
	 */
	public long getInvoiceId();

	/**
	 * Sets the invoice ID of this kolanot invoice line.
	 *
	 * @param invoiceId the invoice ID of this kolanot invoice line
	 */
	public void setInvoiceId(long invoiceId);

	/**
	 * Returns the company ID of this kolanot invoice line.
	 *
	 * @return the company ID of this kolanot invoice line
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this kolanot invoice line.
	 *
	 * @param companyId the company ID of this kolanot invoice line
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the line num of this kolanot invoice line.
	 *
	 * @return the line num of this kolanot invoice line
	 */
	public int getLineNum();

	/**
	 * Sets the line num of this kolanot invoice line.
	 *
	 * @param lineNum the line num of this kolanot invoice line
	 */
	public void setLineNum(int lineNum);

	/**
	 * Returns the item code of this kolanot invoice line.
	 *
	 * @return the item code of this kolanot invoice line
	 */
	@AutoEscape
	public String getItemCode();

	/**
	 * Sets the item code of this kolanot invoice line.
	 *
	 * @param itemCode the item code of this kolanot invoice line
	 */
	public void setItemCode(String itemCode);

	/**
	 * Returns the item name of this kolanot invoice line.
	 *
	 * @return the item name of this kolanot invoice line
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this kolanot invoice line.
	 *
	 * @param itemName the item name of this kolanot invoice line
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the quantity of this kolanot invoice line.
	 *
	 * @return the quantity of this kolanot invoice line
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this kolanot invoice line.
	 *
	 * @param quantity the quantity of this kolanot invoice line
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the price of this kolanot invoice line.
	 *
	 * @return the price of this kolanot invoice line
	 */
	public BigDecimal getPrice();

	/**
	 * Sets the price of this kolanot invoice line.
	 *
	 * @param price the price of this kolanot invoice line
	 */
	public void setPrice(BigDecimal price);

	/**
	 * Returns the discount percent of this kolanot invoice line.
	 *
	 * @return the discount percent of this kolanot invoice line
	 */
	public BigDecimal getDiscountPercent();

	/**
	 * Sets the discount percent of this kolanot invoice line.
	 *
	 * @param discountPercent the discount percent of this kolanot invoice line
	 */
	public void setDiscountPercent(BigDecimal discountPercent);

	/**
	 * Returns the line total of this kolanot invoice line.
	 *
	 * @return the line total of this kolanot invoice line
	 */
	public BigDecimal getLineTotal();

	/**
	 * Sets the line total of this kolanot invoice line.
	 *
	 * @param lineTotal the line total of this kolanot invoice line
	 */
	public void setLineTotal(BigDecimal lineTotal);

	/**
	 * Returns the sales order ID of this kolanot invoice line.
	 *
	 * @return the sales order ID of this kolanot invoice line
	 */
	@AutoEscape
	public String getSalesOrderID();

	/**
	 * Sets the sales order ID of this kolanot invoice line.
	 *
	 * @param salesOrderID the sales order ID of this kolanot invoice line
	 */
	public void setSalesOrderID(String salesOrderID);

	/**
	 * Returns the sales order doc num of this kolanot invoice line.
	 *
	 * @return the sales order doc num of this kolanot invoice line
	 */
	@AutoEscape
	public String getSalesOrderDocNum();

	/**
	 * Sets the sales order doc num of this kolanot invoice line.
	 *
	 * @param salesOrderDocNum the sales order doc num of this kolanot invoice line
	 */
	public void setSalesOrderDocNum(String salesOrderDocNum);

	/**
	 * Returns the sales order line num of this kolanot invoice line.
	 *
	 * @return the sales order line num of this kolanot invoice line
	 */
	public int getSalesOrderLineNum();

	/**
	 * Sets the sales order line num of this kolanot invoice line.
	 *
	 * @param salesOrderLineNum the sales order line num of this kolanot invoice line
	 */
	public void setSalesOrderLineNum(int salesOrderLineNum);

	/**
	 * Returns the sales order qty of this kolanot invoice line.
	 *
	 * @return the sales order qty of this kolanot invoice line
	 */
	public int getSalesOrderQty();

	/**
	 * Sets the sales order qty of this kolanot invoice line.
	 *
	 * @param salesOrderQty the sales order qty of this kolanot invoice line
	 */
	public void setSalesOrderQty(int salesOrderQty);

}