/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kolanot.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.math.BigDecimal;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KolanotInvoice service. Represents a row in the &quot;kolanot_KolanotInvoice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kolanot.service.model.impl.KolanotInvoiceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kolanot.service.model.impl.KolanotInvoiceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KolanotInvoice
 * @generated
 */
@ProviderType
public interface KolanotInvoiceModel
	extends BaseModel<KolanotInvoice>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kolanot invoice model instance should use the {@link KolanotInvoice} interface instead.
	 */

	/**
	 * Returns the primary key of this kolanot invoice.
	 *
	 * @return the primary key of this kolanot invoice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this kolanot invoice.
	 *
	 * @param primaryKey the primary key of this kolanot invoice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this kolanot invoice.
	 *
	 * @return the uuid of this kolanot invoice
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this kolanot invoice.
	 *
	 * @param uuid the uuid of this kolanot invoice
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this kolanot invoice.
	 *
	 * @return the external reference code of this kolanot invoice
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this kolanot invoice.
	 *
	 * @param externalReferenceCode the external reference code of this kolanot invoice
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the invoice ID of this kolanot invoice.
	 *
	 * @return the invoice ID of this kolanot invoice
	 */
	public long getInvoiceId();

	/**
	 * Sets the invoice ID of this kolanot invoice.
	 *
	 * @param invoiceId the invoice ID of this kolanot invoice
	 */
	public void setInvoiceId(long invoiceId);

	/**
	 * Returns the group ID of this kolanot invoice.
	 *
	 * @return the group ID of this kolanot invoice
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this kolanot invoice.
	 *
	 * @param groupId the group ID of this kolanot invoice
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this kolanot invoice.
	 *
	 * @return the company ID of this kolanot invoice
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this kolanot invoice.
	 *
	 * @param companyId the company ID of this kolanot invoice
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by account ID of this kolanot invoice.
	 *
	 * @return the created by account ID of this kolanot invoice
	 */
	public long getCreatedByAccountId();

	/**
	 * Sets the created by account ID of this kolanot invoice.
	 *
	 * @param createdByAccountId the created by account ID of this kolanot invoice
	 */
	public void setCreatedByAccountId(long createdByAccountId);

	/**
	 * Returns the account external reference code of this kolanot invoice.
	 *
	 * @return the account external reference code of this kolanot invoice
	 */
	@AutoEscape
	public String getAccountExternalReferenceCode();

	/**
	 * Sets the account external reference code of this kolanot invoice.
	 *
	 * @param accountExternalReferenceCode the account external reference code of this kolanot invoice
	 */
	public void setAccountExternalReferenceCode(
		String accountExternalReferenceCode);

	/**
	 * Returns the reference no of this kolanot invoice.
	 *
	 * @return the reference no of this kolanot invoice
	 */
	@AutoEscape
	public String getReferenceNo();

	/**
	 * Sets the reference no of this kolanot invoice.
	 *
	 * @param referenceNo the reference no of this kolanot invoice
	 */
	public void setReferenceNo(String referenceNo);

	/**
	 * Returns the created by of this kolanot invoice.
	 *
	 * @return the created by of this kolanot invoice
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this kolanot invoice.
	 *
	 * @param createdBy the created by of this kolanot invoice
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the create date of this kolanot invoice.
	 *
	 * @return the create date of this kolanot invoice
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this kolanot invoice.
	 *
	 * @param createDate the create date of this kolanot invoice
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this kolanot invoice.
	 *
	 * @return the modified date of this kolanot invoice
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this kolanot invoice.
	 *
	 * @param modifiedDate the modified date of this kolanot invoice
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the document number of this kolanot invoice.
	 *
	 * @return the document number of this kolanot invoice
	 */
	@AutoEscape
	public String getDocumentNumber();

	/**
	 * Sets the document number of this kolanot invoice.
	 *
	 * @param documentNumber the document number of this kolanot invoice
	 */
	public void setDocumentNumber(String documentNumber);

	/**
	 * Returns the document status of this kolanot invoice.
	 *
	 * @return the document status of this kolanot invoice
	 */
	@AutoEscape
	public String getDocumentStatus();

	/**
	 * Sets the document status of this kolanot invoice.
	 *
	 * @param documentStatus the document status of this kolanot invoice
	 */
	public void setDocumentStatus(String documentStatus);

	/**
	 * Returns the document date of this kolanot invoice.
	 *
	 * @return the document date of this kolanot invoice
	 */
	public Date getDocumentDate();

	/**
	 * Sets the document date of this kolanot invoice.
	 *
	 * @param documentDate the document date of this kolanot invoice
	 */
	public void setDocumentDate(Date documentDate);

	/**
	 * Returns the due date of this kolanot invoice.
	 *
	 * @return the due date of this kolanot invoice
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this kolanot invoice.
	 *
	 * @param dueDate the due date of this kolanot invoice
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the carrier of this kolanot invoice.
	 *
	 * @return the carrier of this kolanot invoice
	 */
	@AutoEscape
	public String getCarrier();

	/**
	 * Sets the carrier of this kolanot invoice.
	 *
	 * @param carrier the carrier of this kolanot invoice
	 */
	public void setCarrier(String carrier);

	/**
	 * Returns the tracking number of this kolanot invoice.
	 *
	 * @return the tracking number of this kolanot invoice
	 */
	@AutoEscape
	public String getTrackingNumber();

	/**
	 * Sets the tracking number of this kolanot invoice.
	 *
	 * @param trackingNumber the tracking number of this kolanot invoice
	 */
	public void setTrackingNumber(String trackingNumber);

	/**
	 * Returns the sub total of this kolanot invoice.
	 *
	 * @return the sub total of this kolanot invoice
	 */
	public BigDecimal getSubTotal();

	/**
	 * Sets the sub total of this kolanot invoice.
	 *
	 * @param subTotal the sub total of this kolanot invoice
	 */
	public void setSubTotal(BigDecimal subTotal);

	/**
	 * Returns the freight amount of this kolanot invoice.
	 *
	 * @return the freight amount of this kolanot invoice
	 */
	public BigDecimal getFreightAmount();

	/**
	 * Sets the freight amount of this kolanot invoice.
	 *
	 * @param freightAmount the freight amount of this kolanot invoice
	 */
	public void setFreightAmount(BigDecimal freightAmount);

	/**
	 * Returns the gst of this kolanot invoice.
	 *
	 * @return the gst of this kolanot invoice
	 */
	public BigDecimal getGst();

	/**
	 * Sets the gst of this kolanot invoice.
	 *
	 * @param gst the gst of this kolanot invoice
	 */
	public void setGst(BigDecimal gst);

	/**
	 * Returns the invoice total of this kolanot invoice.
	 *
	 * @return the invoice total of this kolanot invoice
	 */
	public BigDecimal getInvoiceTotal();

	/**
	 * Sets the invoice total of this kolanot invoice.
	 *
	 * @param invoiceTotal the invoice total of this kolanot invoice
	 */
	public void setInvoiceTotal(BigDecimal invoiceTotal);

	/**
	 * Returns the balance due of this kolanot invoice.
	 *
	 * @return the balance due of this kolanot invoice
	 */
	public BigDecimal getBalanceDue();

	/**
	 * Sets the balance due of this kolanot invoice.
	 *
	 * @param balanceDue the balance due of this kolanot invoice
	 */
	public void setBalanceDue(BigDecimal balanceDue);

	/**
	 * Returns the tracking url of this kolanot invoice.
	 *
	 * @return the tracking url of this kolanot invoice
	 */
	@AutoEscape
	public String getTrackingURL();

	/**
	 * Sets the tracking url of this kolanot invoice.
	 *
	 * @param trackingURL the tracking url of this kolanot invoice
	 */
	public void setTrackingURL(String trackingURL);

	/**
	 * Returns the status of this kolanot invoice.
	 *
	 * @return the status of this kolanot invoice
	 */
	public int getStatus();

	/**
	 * Sets the status of this kolanot invoice.
	 *
	 * @param status the status of this kolanot invoice
	 */
	public void setStatus(int status);

	/**
	 * Returns the paid sum of this kolanot invoice.
	 *
	 * @return the paid sum of this kolanot invoice
	 */
	public BigDecimal getPaidSum();

	/**
	 * Sets the paid sum of this kolanot invoice.
	 *
	 * @param paidSum the paid sum of this kolanot invoice
	 */
	public void setPaidSum(BigDecimal paidSum);

	/**
	 * Returns the file entry ID of this kolanot invoice.
	 *
	 * @return the file entry ID of this kolanot invoice
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this kolanot invoice.
	 *
	 * @param fileEntryId the file entry ID of this kolanot invoice
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the billing address ID of this kolanot invoice.
	 *
	 * @return the billing address ID of this kolanot invoice
	 */
	public long getBillingAddressId();

	/**
	 * Sets the billing address ID of this kolanot invoice.
	 *
	 * @param billingAddressId the billing address ID of this kolanot invoice
	 */
	public void setBillingAddressId(long billingAddressId);

	/**
	 * Returns the shipping address ID of this kolanot invoice.
	 *
	 * @return the shipping address ID of this kolanot invoice
	 */
	public long getShippingAddressId();

	/**
	 * Sets the shipping address ID of this kolanot invoice.
	 *
	 * @param shippingAddressId the shipping address ID of this kolanot invoice
	 */
	public void setShippingAddressId(long shippingAddressId);

}